Unit Tests: `expect( 'wp_localize_script' )` (#117)
Fixes:
```
There was 1 error:

1) Automattic\Gravatar\GravatarEnhanced\Hovercards\HovercardsTest::testGravatarEnhancedAddHovercards_WhenEnabled_ThenEnqueuesScripts
Error: Call to undefined function Automattic\Gravatar\GravatarEnhanced\Hovercards\wp_localize_script()

/Users/a8c/Checkouts/gravatar-enhanced/classes/hovercards/class-hovercards.php:114
/Users/a8c/Checkouts/gravatar-enhanced/tests/unit/classes/hovercards/class-hovercards-test.php:93
```